config:
  target: "http://localhost:3000"
  http: 
    pool: 20
  phases:
    - duration: 10
      arrivalRate: 10
      rampTo: 100
      name: "Warm up the application"
    - duration: 60
      arrivalRate: 100
      name: "Sustained load"

scenarios:
  - name: "Get product"
    flow:
      - get:
          url: "/"